export const testimonials = [
  {
    text: "Eric est un coach qui tient ses promesses: il met tout en œuvre pour que nous atteignons nos objectifs. Ses entraînements sont exigeants, mais toujours menés dans la bonne humeur et toujours dans l’esprit de « kiffer sa Life ». Il sait transmettre son amour de la course à pied et du trail, et fait preuve d’une grande écoute. Mais s’il ne fallait retenir qu’une seule qualité parmi toutes celles qui font sa force, ce serait sa capacité à nous projeter vers des objectifs que nous n’aurions même pas osé nous fixer nous-mêmes. Il nous aide à voir plus loin, plus grand, et finit souvent par nous convaincre que nous sommes capables de bien plus que ce que nous imaginions.",
    author: "Radia CL.",
    meta: "",
    initials: "RCL",
    rating: 5,
  },
  {text:"Eric partage sa passion pour le running et le trail. Pour lui, c'est plus qu'un sport, c'est un mode de vie et une philosophie de vie. Son accompagnement va bien au-delà d'un simple programme d'entraînement. Il adapte les séances au rythme, aux capacités et aux objectifs de chacun : préparation spécifique, séances de renforcement, progressivité, écoute et gestion de la charge. Au-delà de son expertise technique, Eric est un coach au grand cœur. Ce qui m'a le plus portée dans mes préparations, ce sont ses messages que j'attendais après chaque séance. Il est coach mental autant que coach physique. Il a su m'aider à dépasser mes doutes, à vaincre ma peur du vide quand je me suis lancée en trail, à croire en moi quand je n'y croyais plus. J'ajouterai qu'il est rigoureux, présent, dans un suivi très rapproché, toujours disponible, que ce soit pour ajuster une séance, débriefer une séance/course ou simplement rassurer et encourager avant un départ. Merci Eric. Merci pour les kilomètres, pour les chronos, et surtout pour toutes les émotions vécues durant mes courses.",
   author:"Jihane R",
   meta:"",
   initials:"JR",
   rating: 5,
  },
  {text:"Cher Eric, À quelques jours du trail de Chefchaouen, je voulais prendre un moment pour te dire merci du fond du cœur. Merci pour ta bienveillance, ton dévouement, ton accueil et ton accompagnement. Merci pour ta présence, qu’on appréhendait parfois de peur de te décevoir 😅 mais qui a finalement fait une vraie différence dans les séances difficiles. Grâce à toi, j’ai pu arriver au bout de cette préparation sans blessure, ce qui est déjà une vraie victoire pour moi. Merci pour tous les feedbacks que Selma me transfère après les séances je les reçois souvent au travail, et ils me redonnent le sourire et m’aident vraiment à garder le cap. J’ai déjà fait d’autres trails, mais celui-ci est différent. Je l’aborde avec beaucoup moins d’appréhension et surtout beaucoup plus de confiance. Grâce à toi, je me sens prête à vivre cette aventure autrement. Merci pour tout coach 🙏🙏",
   author:"Amal M",
   meta:"",
   initials:"AM",
   rating:5,
  },
  {text:"Un immense merci à Eric pour son accompagnement sur mes trails et semi-marathons. Grâce à lui, j’ai atteint des objectifs que je ne pensais pas accessibles. Un coach profondément humain, passionné et toujours juste dans ses conseils, que je recommande sans hésiter à toutes celles et ceux qui souhaitent progresser dans un cadre à la fois challengeant et rassurant. Un vrai plaisir de progresser à ses côtés.",
  author:"Salma B",
  meta:"",
  initials:"SB",
  rating:5,
 },
  {
    text: "Éric m’a notamment accompagné dans la préparation d’un semi-marathon puis d’un marathon. Dès le départ, il a su construire un programme parfaitement adapté à mon niveau, tout en l’ajustant au fil des semaines en fonction de mon évolution et de mes sensations. Grâce à son suivi précis, j’ai pu progresser constamment sans jamais tomber dans le surentraînement ou la saturation. Éric est un coach extrêmement attentif, toujours à l’écoute de ses athlètes, et impliqué dans chaque séance. Mais au-delà du coach, il y a surtout l’humain : celui qui croit sincèrement en nous, qui nous pousse à prendre confiance en nous-mêmes et à nous dépasser à travers le running. Avoir Éric à ses côtés pour préparer de tels objectifs est une vraie chance. Mon rapport à la course à pied a complètement changé depuis que je suis suivi par lui, et je ne le remercierai jamais assez pour l’impact qu’il a eu sur ma pratique et ma confiance en moi.",
    author: "Manon S.",
    meta: "Préparation Semi-marathon puis Marathon",
    initials: "MS",
    rating: 5,
  },
  {
    text: "J'ai été suivi par Eric sur plusieurs objectifs de running différents. Le premier a été de retrouver un rythme de course agréable après plus d'un an et demi d'arrêt, avec pour objectif un marathon en 4h, réussi haut la main ! Ensuite, l'objectif était de réussir un RP sur semi-marathon en 1h45, également atteint, et surtout sans douleur ! Eric m'a accompagné après chaque sortie afin de m'aider à progresser, éviter les douleurs et améliorer ma FC. Le suivi s'est fait à distance, mais avec un échange constant, beaucoup de conseils et d'encouragements. Je le recommande pour tous vos objectifs : il saura adapter vos programmes à votre niveau et vous accompagner vers vos réussites.",
    author: "Mélanie B.",
    meta: "Marathon 4h & Semi en 1h45",
    initials: "MB",
    rating: 5,
  },
  {
    text: "Salam Éric, merci encore pour ton coaching ! C'était ma première expérience en trail et honnêtement tu as réussi à me mettre en confiance dès le début. Les séances théoriques, pratiques et les entraînements organisés avant le trail ont vraiment fait la différence. On sent la passion, le sérieux et le vrai accompagnement derrière tout ça. Grâce à toi, j'ai découvert le trail dans les meilleures conditions et ça m'a donné envie de continuer 😅",
    author: "Jawad A.",
    meta: "Sika Maroc — Trail Lalla Takerkoust 2026",
    initials: "JA",
    rating: 5,
  },
  {
    text: "Un grand merci pour la bonne organisation du trail de Takerkoust et pour l'accompagnement tout au long de la préparation. Ton coaching a été excellent : séances efficaces, conseils pertinents et une vraie motivation transmise au groupe, avec en plus l'immortalisation des séances d'entraînement à travers de superbes photos. Bravo pour ton professionnalisme et ton engagement.",
    author: "Merieme E.",
    meta: "Sika Maroc — Trail Lalla Takerkoust 2026",
    initials: "ME",
    rating: 5,
  },

  {
    text: "Commencer le trail me faisait un peu peur, mais Eric a su me mettre en confiance immédiatement. Son coaching sur-mesure m'a permis de progresser à mon rythme, sans me blesser et en y prenant un plaisir fou. Grâce à son écoute et ses conseils, je me sens aujourd'hui capable de franchir de nouveaux sommets. Merci Eric !.",
    author: "Saad I.",
    meta: "Sika Maroc — Trail Lalla Takerkoust 2026",
    initials: "SI",
    rating: 5,
  },
  {
    text: "Quand j’ai rejoint la section running du CAFC, mon objectif était clair : réussir mon premier marathon. Éric m’a accompagné dès le début avec un coaching vraiment top. Au-delà de ses grandes connaissances techniques, il sait surtout adapter son accompagnement à la personne qu’il a en face de lui. Ses conseils étaient toujours précis, ses relances intelligentes, et il assurait un vrai suivi tout au long de la préparation. Grâce à lui, je ne me suis jamais blessé pendant toute ma préparation, ce qui est assez remarquable sur un projet aussi exigeant qu’un marathon. Éric ne se contente pas de donner des plans d’entraînement : il transmet de la confiance, de la méthode et une vraie passion pour la course à pied. Son sérieux, son écoute et son expérience m’ont permis d’aller au bout de mon défi dans les meilleures conditions. Je recommande Éric à toute personne souhaitant progresser en course à pied, que ce soit pour préparer une première course ou viser un objectif ambitieux.",
    author: "Omar S.",
    meta: "Marathon de Malaga 2026",
    initials: "OS",
    rating: 5,
  },
  {
    text: "Un grand merci au coach Eric pour son accompagnement dans la préparation du Trail de Takerkoust (21 km avec 500 m de dénivelé positif). Grâce à ses séances variées et adaptées, mêlant gammes, fractionnés en côte et sorties longues, nous avons pu progresser efficacement et arriver prêts le jour de la course. Son expertise, ses conseils et sa motivation ont été précieux tout au long de cette préparation. Je le recommande vivement à tous ceux qui souhaitent atteindre leurs objectifs en course à pied et en trail.",
    author: "Mohamed Amine C.",
    meta: "Trail Lalla Takerkoust 2026",
    initials: "MAC",
    rating: 5,
  },
];

export const packs = [
  {
    type: "distance",
    name: "Prépa Semi-marathon & Marathon",
    icon: "timer",
    subtitle: "Durée : 10 à 12 semaines",
    description: "Un suivi complet depuis n'importe où dans le monde.",
    features: [
      "Plan d'entraînement personnalisé et évolutif",
      "Suivi téléphonique au besoin",
      "Messagerie directe (réponse sous 24h)",
      "1 appel bilan mensuel (30 min)",
      "Analyse des données de course après chaque séance",
      "Conseils nutrition & récupération",
      "Adaptation du plan en continu selon tes retours",
      "Conseil stratégie de course",
      "Une séance présentielle hebdomadaire",
    ],
    cta: "Je me lance",
  },
  {
    type: "distance",
    name: "Prépa Trail",
    icon: "mountain",
    subtitle: "Durée : à déterminer selon objectif",
    description: "Un suivi complet depuis n'importe où dans le monde.",
    features: [
      "Plan d'entraînement personnalisé et évolutif accès trail",
      "Séance PMA",
      "Ajout de séance vélo",
      "Suivi téléphonique au besoin",
      "Messagerie directe (réponse sous 24h)",
      "1 appel bilan mensuel (30 min)",
      "Analyse des données de course après chaque séance",
      "Conseils nutrition, récupération & renforcement musculaire",
      "Adaptation du plan en continu selon tes retours",
      "Une séance présentielle hebdomadaire",
    ],
    cta: "Je me lance",
  },
  {
    type: "presentiel",
    name: "Pack Mensuel",
    icon: "calendar",
    subtitle: "Durée : mensuel",
    description: "Un coaching terrain au plus près de toi. Des séances encadrées pour corriger, progresser et repousser tes limites ensemble.",
    features: [
      "Amélioration foulée",
      "Amélioration VMA",
      "Reprise après arrêt prolongé",
      "Entretien entre 2 objectifs",
      "Débutants",
      "Plan d'entraînement personnalisé",
      "Suivi des performances et ajustements",
    ],
    cta: "Je me lance",
  },
  {
    type: "presentiel",
    name: "Séance présentielle",
    icon: "users",
    subtitle: "Durée : 1h ou forfait 10 séances*",
    description: "Un coaching terrain au plus près de toi. Des séances encadrées pour corriger, progresser et repousser tes limites ensemble.",
    features: [
      "Séances d'entraînement encadrées sur le terrain",
      "Coaching technique running & trail",
    ],
    footnote: "* Validité de 3 mois",
    cta: "Je me lance",
  },
];

export const faqItems = [
  {
    q: "Comment se passe le paiement ?",
    a: "Le paiement s’effectue au début du mois.",
  },
  {
    q: "Va t’il y avoir un entretien pré-coaching ?",
    a: "Oui, il y aura bien un entretien téléphonique durant lequel nous parlerons de vos besoins et attentes.",
  },
  {
    q: "Est-ce que le coaching convient si je sors d'une blessure ?",
    a: "Oui, tout à fait, mais seulement après accord de votre médecin ou kiné.",
  },
  {
    q: "Quelle application utilisez-vous pour le suivi ?",
    a: "J'utilise habituellement GARMIN, mais si vous avez une autre marque de montre, je m'adapte.",
  },
  {
    q: "Peut-on changer de pack en cours de route ?",
    a: "Oui, on peut changer de formule à n'importe quel moment, après discussions.",
  },
  {
    q: "Y a-t-il un engagement de durée minimum ?",
    a: "Uniquement pour le pack mensuel.",
  },
];

export const quotes = [
  { text: "Certains veulent que ça arrive. D'autres aimeraient que ça arrive. Et les autres font que ça arrive.", author: "Michael Jordan" },
  { text: "Si tu veux courir, cours un kilomètre. Si tu veux changer ta vie, cours un marathon.", author: "Emil Zátopek" },
  { text: "Toute chose longue et difficile n'est que la somme de choses courtes et faciles.", author: "René Descartes" },
  { text: "Là où il y a une volonté, il y a un chemin.", author: null },
  { text: "Les deux guerriers les plus puissants sont la patience et le temps.", author: "Léon Tolstoï" },
  { text: "Never run faster than your guardian angel can fly.", author: null },
  { text: "If your dreams don't scare you, they are not big enough.", author: "Ellen Johnson Sirleaf" },
];
